.TH TINYWM "1" "March 2005"
.SH NAME
tinywm \- tiny window manager
.SH SYNOPSIS
.B tinywm
.SH DESCRIPTION
\fBTinyWM\fP is a small, simple window manager.  It has a minimal memory
footprint, which makes it useful in embedded systems.  It features window
move, resize, and raise operations, and supports "sloppy focus".
.
Due to its simplicity, its source code (in C and Python) can be used as a
reference implementation for developers seeking to understand basic window
manager programming.

.SH USAGE
.TP
Focus follows pointer.
.TP
Alt+Button1, drag: interactive window move
.TP
Alt+Button3, drag: interactive window resize
.TP
Alt+F1: raise focused window
.SH AUTHOR
This manual page was written by Nobuhiro Iwamatsu <hemamu@t-base.ne.jp>,
for the Debian GNU/Linux system (but may be used by others).
